<!-- checkout page -->
<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12" style="margin-top: 30px">	
			<h3 style="font-weight: bold">CHÍNH SÁCH ĐỔI TRẢ HÀNG</h3>
			<div style="margin-top: 25px; margin-bottom: 55px">
				<img src="<?=$_SESSION['projectName']?>/lib/images/chinh_sach_doi_tra.jpg" alt="error" style="width:380px; height: 250px;" />
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box; font-size: 11pt; font-family: arial, helvetica, sans-serif;">Nhằm đảm bảo quyền lợi tốt nhất cho đồng tiền m&agrave; kh&aacute;ch h&agrave;ng chi ra để mua c&aacute;c sản phẩm tại Nlink. Ch&uacute;ng t&ocirc;i c&oacute; ch&iacute;nh s&aacute;ch đổi / trả h&agrave;ng với c&aacute;c quy định cụ thể sau đ&acirc;y:</span></p>
				<h3 style="box-sizing: border-box; font-family: Arial, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(51, 51, 51); margin: 15px auto 10px; font-size: 24px; display: block; padding-bottom: 2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box; font-size: 12pt;"><strong style="box-sizing: border-box; font-weight: 700;">I. C&aacute;c trường hợp &aacute;p dụng đổi/trả sản phẩm</strong></span>:</h3>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 700;">1. Đổi/trả sản phẩm khi sản phẩm c&oacute; lỗi, sai quy c&aacute;ch</strong></p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Nlink &aacute;p dụng phương thức đổi/ trả sản phẩm trong trường hợp sản phẩm nhận được bị lỗi (bao b&igrave; kh&aacute;c so với m&ocirc; tả tr&ecirc;n website, sản phẩm kh&aacute;c so với sản phẩm đ&atilde; đặt, sản phẩm bị r&aacute;ch, lỗi do nh&agrave; sản xuất). Qu&yacute; kh&aacute;ch vui l&ograve;ng li&ecirc;n hệ tới Nlink để được hỗ trợ.&nbsp;</p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Trong v&ograve;ng 48 giờ kể từ khi nhận h&agrave;ng qu&yacute; kh&aacute;ch vui l&ograve;ng li&ecirc;n hệ với ch&uacute;ng t&ocirc;i để được hỗ trợ. Sau 48h kể từ ng&agrave;y qu&yacute; kh&aacute;ch nhận được h&agrave;ng, Nlink từ chối hỗ trợ c&aacute;c khiếu nại theo nội dung tr&ecirc;n</p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Trong trường hợp n&agrave;y Qu&yacute; kh&aacute;ch&nbsp;<strong style="box-sizing: border-box; font-weight: 700;">ĐƯỢC QUYỀN ĐỔI</strong> sang sản phẩm c&ugrave;ng loại hoặc sản phẩm kh&aacute;c c&oacute; gi&aacute; trị tương đương hoặc lớn hơn so với sản phẩm đ&atilde; đặt. Ch&uacute; &yacute; trong trường hợp đổi sang sản phẩm c&oacute; gi&aacute; trị lớn hơn qu&yacute; kh&aacute;ch cần thanh to&aacute;n th&ecirc;m phần chi ph&iacute; ch&ecirc;nh lệch so với sản phẩm cũ.</p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 700;">2. Do nhu cầu kh&aacute;ch h&agrave;ng</strong></p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Nlink&nbsp;<strong style="box-sizing: border-box; font-weight: 700;">KH&Ocirc;NG</strong> &aacute;p dụng&nbsp;<strong style="box-sizing: border-box; font-weight: 700;">TRẢ H&Agrave;NG</strong> trong trường hợp kh&aacute;ch h&agrave;ng kh&ocirc;ng c&oacute; nhu cầu sử dụng hoặc nhu cầu mua sản phẩm. Nếu sản phẩm vẫn đ&aacute;p ứng y&ecirc;u cầu h&agrave;ng h&oacute;a khi đổi trả tại Nlink qu&yacute; kh&aacute;ch&nbsp;<strong style="box-sizing: border-box; font-weight: 700;">ĐƯỢC QUYỀN ĐỔI</strong> sang sản phẩm c&oacute; gi&aacute; trị tương đương hoặc lớn hơn (cần thanh to&aacute;n th&ecirc;m chi ph&iacute; ch&ecirc;nh lệch nếu gi&aacute; trị sản phẩm được đổi c&oacute; gi&aacute; trị cao hơn)</p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 700;">3.&nbsp;Đổi h&agrave;ng lỗi do qu&aacute; tr&igrave;nh vận chuyển</strong></p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box; color: rgb(255, 0, 0);">Khi nhận được sản phẩm Qu&yacute; kh&aacute;ch vui l&ograve;ng KIỂM TRA NGAY KHI SHIP GIAO H&Agrave;NG. C&oacute; bất cứ vấn đề g&igrave; về h&agrave;ng h&oacute;a vui l&ograve;ng LI&Ecirc;N HỆ NGAY với Nlink tại thời điểm đ&oacute; hoặc trả h&agrave;ng nếu h&agrave;ng bị lỗi.</span></p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box; color: rgb(255, 0, 0);">Nlink &aacute;p dụng phương thức COD (<strong style="box-sizing: border-box; font-weight: 700;">được kiểm tra h&agrave;ng trước khi nhận</strong>) n&ecirc;n Qu&yacute; kh&aacute;ch ho&agrave;n to&agrave;n c&oacute; thể kiểm tra h&agrave;ng trước khi nhận. Trường hợp đ&atilde; c&oacute; bi&ecirc;n bản đồng kiểm giữa nh&agrave; vận chuyển v&agrave; người mua, Nlink sẽ kh&ocirc;ng hỗ trợ đổi h&agrave;ng trong mọi điều kiện.</span></p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 700;">4. Bảo h&agrave;nh sản phẩm do lỗi nh&agrave; cung cấp</strong></p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Ch&uacute;ng t&ocirc;i &aacute;p dụng h&igrave;nh thức bảo h&agrave;nh cho sản phẩm đạt c&aacute;c ti&ecirc;u ch&iacute; sau</p>
				<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; padding-left: 20px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
					<li style="box-sizing: border-box; margin-left: auto;">Sản phẩm&nbsp;mua h&agrave;ng tại Nlink</li>
					<li style="box-sizing: border-box; margin-left: auto;">Sản phẩm c&oacute; ch&iacute;nh s&aacute;ch bảo h&agrave;nh</li>
					<li style="box-sizing: border-box; margin-left: auto;">Sản phẩm c&ograve;n nguy&ecirc;n tem bảo h&agrave;nh, h&oacute;a đơn mua h&agrave;ng</li>
					<li style="box-sizing: border-box; margin-left: auto;">Sản phẩm c&ograve;n thời gian bảo h&agrave;nh theo quy định</li>
					<li style="box-sizing: border-box; margin-left: auto;">Sản phẩm lỗi kỹ thuật do nh&agrave; sản xuất, KH&Ocirc;NG bảo h&agrave;nh c&aacute;c lỗi hỏng h&oacute;c do người sử dụng: l&agrave;m rơi, l&agrave;m vỡ, sử dụng sai hướng dấn v&agrave; quy c&aacute;ch</li>
					<li style="box-sizing: border-box; margin-left: auto;">Thời hạn bảo h&agrave;nh t&ugrave;y theo từng sản phẩm</li>
				</ul>
				<h3 style="box-sizing: border-box; font-family: Arial, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(51, 51, 51); margin: 15px auto 10px; font-size: 24px; display: block; padding-bottom: 2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box; font-size: 12pt;"><strong style="box-sizing: border-box; font-weight: 700;">II.&nbsp;Y&ecirc;u cầu sản phẩm khi đổi trả</strong></span></h3>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">- Sản phẩm kh&ocirc;ng c&oacute; dấu hiệu đ&atilde; qua sử dụng, c&ograve;n nguy&ecirc;n tem, m&aacute;c hay ni&ecirc;m phong của nh&agrave; sản xuất</p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">- Sản phẩm c&ograve;n đầy đủ phụ kiện, tem hoặc phiếu bảo h&agrave;nh c&ugrave;ng qu&agrave; tặng k&egrave;m theo (nếu c&oacute;).</p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">- Tiến h&agrave;nh gửi lại để đổi v&agrave; trả h&agrave;ng trong 5 ng&agrave;y kể từ thời điểm giao h&agrave;ng th&agrave;nh c&ocirc;ng</p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">- Danh mục&nbsp;<strong style="box-sizing: border-box; font-weight: 700;">KH&Ocirc;NG</strong> &aacute;p dụng h&igrave;nh thức đổi/trả bao gồm</p>
				<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; padding-left: 20px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
					<li style="box-sizing: border-box; margin-left: auto;">Đồng hồ</li>
					<li style="box-sizing: border-box; margin-left: auto;">T&uacute;i x&aacute;ch</li>
					<li style="box-sizing: border-box; margin-left: auto;">Thời trang</li>
				</ul>
				<h3 style="box-sizing: border-box; font-family: Arial, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(51, 51, 51); margin: 15px auto 10px; font-size: 24px; display: block; padding-bottom: 2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box; font-size: 12pt;"><strong style="box-sizing: border-box; font-weight: 700;">III. Quy tr&igrave;nh đổi trả sản phẩm khi c&oacute; lỗi</strong></span></h3>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Vui l&ograve;ng chắc chắn rằng sản phẩm qu&yacute; kh&aacute;ch y&ecirc;u cầu đổi (trả) thỏa m&atilde;n điều kiện đổi trả h&agrave;ng của Nlink v&agrave; kh&ocirc;ng nằm trrong danh mục sản phẩm kh&ocirc;ng &aacute;p dụng đổi/trả</p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">C&aacute;c bước thực hiện:</p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">- Li&ecirc;n lạc với ch&uacute;ng t&ocirc;i v&agrave; phản &aacute;nh về sản phẩm: Khi li&ecirc;n lạc vui l&ograve;ng cung cấp c&aacute;c th&ocirc;ng tin về sản phẩm gồm:</p>
				<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; padding-left: 20px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
					<li style="box-sizing: border-box; margin-left: auto;">Số điện thoại đặt h&agrave;ng</li>
					<li style="box-sizing: border-box; margin-left: auto;">Tến sản phẩm đ&atilde; đặt</li>
					<li style="box-sizing: border-box; margin-left: auto;">Lỗi sản phẩm (m&ocirc; tả chi tiết v&agrave; k&egrave;m ảnh chụp nếu c&oacute;)</li>
					<li style="box-sizing: border-box; margin-left: auto;">Nhu cầu cần hỗ trợ: Đổi, trả, bảo h&agrave;nh</li>
				</ul>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">- X&aacute;c nhận sản phẩm đạt y&ecirc;u cầu đổi trả</p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Khi được nh&acirc;n vi&ecirc;n phản hồi sản phẩm đạt y&ecirc;u cầu đổi trả, qu&yacute; kh&aacute;ch vui l&ograve;ng đ&oacute;ng g&oacute;i sản phẩm gửi lại sản phẩm qua đường bưu điện hoặc qua trực tiếp cửa h&agrave;ng tại H&agrave; Nội v&agrave; Hồ Ch&iacute; Minh. Qu&yacute; kh&aacute;ch vui l&ograve;ng chịu ph&iacute; vận chuyển đổi trả h&agrave;ng v&agrave; đảm bảo t&iacute;nh nguy&ecirc;n vẹn của sản phẩm khi vận chuyển</p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 700;">Địa chỉ đổi trả h&agrave;ng trực tiếp</strong></p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Số 76, Trần Đình Xu, Phường Cô Giang, Quận 1, TP. Hồ Ch&iacute; Minh</p>
				<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Hotline: 0903.029.313</p>
			</div>
		</div>		
	</div>
</div>	
<!-- //checkout page -->